version: '3.7'

services:
  reverse-proxy:
    container_name: reverse-proxy
    restart: unless-stopped
    image: traefik:2.9
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - ./certs:/certs:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.prometheus.entrypoints=https'
      - 'traefik.http.routers.api.rule=Host(`traefik.aria-portal.local`)'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.aria-portal.local`)'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.prometheus.service=prometheus@internal'
      - 'traefik.http.routers.api.middlewares=auth'
      - 'traefik.http.routers.prometheus.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=aria:$$apr1$$SDRTWUpx$$Zp3fJNakrU307TcRQ7Qau0'
      - 'traefik.http.middlewares.api.ratelimit.average=100'
      - 'traefik.http.middlewares.prometheus.ratelimit.average=100'
      - 'traefik.http.middlewares.api.ratelimit.burst=20'
      - 'traefik.http.middlewares.prometheus.ratelimit.burst=20'
      - 'traefik.http.middlewares.api.headers.customrequestheaders.contentSecurityPolicy="default-src "none"; script-src "none"; script-src-elem "none"; script-src-attr "none"; style-src "none"; style-src-elem "none"; style-src-attr "none"; img-src "none"; font-src "none";"'
      - 'traefik.http.middlewares.prometheus.headers.customrequestheaders.contentSecurityPolicy="default-src "none"; script-src "none"; script-src-elem "none"; script-src-attr "none"; style-src "none"; style-src-elem "none"; style-src-attr "none"; img-src "none"; font-src "none";"'
      - 'traefik.http.middlewares.api.headers.customrequestheaders.accessControlAllowOriginList=traefik.aria-portal.local'
      - 'traefik.http.middlewares.prometheus.headers.customrequestheaders.accessControlAllowOriginList=prometheus.aria-portal.local'
      - 'traefik.http.middlewares.api.headers.customrequestheaders.accessControlAllowMethods=GET, POST, OPTIONS'
      - 'traefik.http.middlewares.prometheus.headers.customrequestheaders.accessControlAllowMethods=GET, POST, OPTIONS'
      - 'traefik.http.middlewares.api.headers.customrequestheaders.accessControlAllowCredentials=true'
      - 'traefik.http.middlewares.prometheus.headers.customrequestheaders.accessControlAllowCredentials=true'
      - 'traefik.http.middlewares.api.headers.customrequestheaders.accessControlMaxAge=100'
      - 'traefik.http.middlewares.prometheus.headers.customrequestheaders.accessControlMaxAge=100'
      - 'traefik.http.middlewares.api.headers.customrequestheaders.browserXssFilter=true'
      - 'traefik.http.middlewares.prometheus.headers.customrequestheaders.browserXssFilter=true'
      - 'traefik.http.middlewares.api.headers.customrequestheaders.frameDeny=true'
      - 'traefik.http.middlewares.prometheus.headers.customrequestheaders.frameDeny=true'
    depends_on:
      - nginx

  grafana:
    container_name: grafana
    restart: on-failure
    image: grafana/grafana-oss:9.2.0-beta1-ubuntu
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.entrypoints=https'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.aria-portal.local`)'
      - 'traefik.http.routers.grafana.tls=true'
      - 'traefik.http.middlewares.grafana.ratelimit.average=100'
      - 'traefik.http.middlewares.grafana.ratelimit.burst=20'
      - 'traefik.http.middlewares.grafana.headers.customrequestheaders.contentSecurityPolicy="default-src "none"; script-src "none"; script-src-elem "none"; script-src-attr "none"; style-src "none"; style-src-elem "none"; style-src-attr "none"; img-src "none"; font-src "none";"'
      - 'traefik.http.middlewares.grafana.headers.customrequestheaders.accessControlAllowOriginList=grafana.aria-portal.local'
      - 'traefik.http.middlewares.grafana.headers.customrequestheaders.accessControlAllowMethods=GET, POST, OPTIONS'
      - 'traefik.http.middlewares.grafana.headers.customrequestheaders.accessControlAllowCredentials=true'
      - 'traefik.http.middlewares.grafana.headers.customrequestheaders.accessControlMaxAge=100'
      - 'traefik.http.middlewares.grafana.headers.customrequestheaders.browserXssFilter=true'
      - 'traefik.http.middlewares.grafana.headers.customrequestheaders.frameDeny=true'
    env_file:
      - ./grafana/grafana.config
    depends_on:
      - cadvisor

  cadvisor:
    container_name: cadvisor
    restart: on-failure
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.cadvisor.entrypoints=https'
      - 'traefik.http.routers.cadvisor.rule=Host(`cadvisor.aria-portal.local`)'
      - 'traefik.http.routers.cadvisor.tls=true'
      - 'traefik.http.routers.cadvisor.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=aria:$$apr1$$SDRTWUpx$$Zp3fJNakrU307TcRQ7Qau0'
      - 'traefik.http.middlewares.cadvisor.ratelimit.average=100'
      - 'traefik.http.middlewares.cadvisor.ratelimit.burst=20'
      - 'traefik.http.middlewares.cadvisor.headers.customrequestheaders.contentSecurityPolicy="default-src "none"; script-src "none"; script-src-elem "none"; script-src-attr "none"; style-src "none"; style-src-elem "none"; style-src-attr "none"; img-src "none"; font-src "none";"'
      - 'traefik.http.middlewares.cadvisor.headers.customrequestheaders.accessControlAllowOriginList=cadvisor.aria-portal.local'
      - 'traefik.http.middlewares.cadvisor.headers.customrequestheaders.accessControlAllowMethods=GET, POST, OPTIONS'
      - 'traefik.http.middlewares.cadvisor.headers.customrequestheaders.accessControlAllowCredentials=true'
      - 'traefik.http.middlewares.cadvisor.headers.customrequestheaders.accessControlMaxAge=100'
      - 'traefik.http.middlewares.cadvisor.headers.customrequestheaders.browserXssFilter=true'
      - 'traefik.http.middlewares.cadvisor.headers.customrequestheaders.frameDeny=true'

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.23
    volumes:
      - ./../portal:/var/www/portal:ro
      - ./portal/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.entrypoints=https'
      - 'traefik.http.routers.nginx.rule=Host(`aria-portal.local`) || Host(`www.aria-portal.local`)'
      - 'traefik.http.routers.nginx.tls=true'
      - 'traefik.http.middlewares.nginx.ratelimit.average=100'
      - 'traefik.http.middlewares.nginx.ratelimit.burst=20'
      - 'traefik.http.middlewares.nginx.headers.customrequestheaders.contentSecurityPolicy="default-src "none"; script-src "none"; script-src-elem "none"; script-src-attr "none"; style-src "none"; style-src-elem "none"; style-src-attr "none"; img-src "none"; font-src "none";"'
      - 'traefik.http.middlewares.nginx.headers.customrequestheaders.accessControlAllowOriginList=aria-portal.local www.aria-portal.local'
      - 'traefik.http.middlewares.nginx.headers.customrequestheaders.accessControlAllowMethods=GET, POST, OPTIONS'
      - 'traefik.http.middlewares.nginx.headers.customrequestheaders.accessControlAllowCredentials=true'
      - 'traefik.http.middlewares.nginx.headers.customrequestheaders.accessControlMaxAge=100'
      - 'traefik.http.middlewares.nginx.headers.customrequestheaders.browserXssFilter=true'
      - 'traefik.http.middlewares.nginx.headers.customrequestheaders.frameDeny=true'
    depends_on:
      - portal

  portal:
    container_name: portal
    restart: unless-stopped
    build:
      context: ./portal
      dockerfile: ./build/Dockerfile
    volumes:
      - ./../portal:/var/www/portal
      - ./portal/php.ini:/usr/local/etc/php/php-production.ini
    labels:
      - 'traefik.enable=true'

  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7.9
    labels:
      - 'traefik.enable=true'
    env_file:
     - ./mysql/mysql.config

  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:5
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.phpmyadmin.entrypoints=https'
      - 'traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.aria-portal.local`)'
      - 'traefik.http.routers.phpmyadmin.tls=true'
      - 'traefik.http.routers.phpmyadmin.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=aria:$$apr1$$SDRTWUpx$$Zp3fJNakrU307TcRQ7Qau0'
      - 'traefik.http.middlewares.phpmyadmin.ratelimit.average=100'
      - 'traefik.http.middlewares.phpmyadmin.ratelimit.burst=20'
      - 'traefik.http.middlewares.phpmyadmin.headers.customrequestheaders.contentSecurityPolicy="default-src "none"; script-src "none"; script-src-elem "none"; script-src-attr "none"; style-src "none"; style-src-elem "none"; style-src-attr "none"; img-src "none"; font-src "none";"'
      - 'traefik.http.middlewares.phpmyadmin.headers.customrequestheaders.accessControlAllowOriginList=phpmyadmin.aria-portal.local'
      - 'traefik.http.middlewares.phpmyadmin.headers.customrequestheaders.accessControlAllowMethods=GET, POST, OPTIONS'
      - 'traefik.http.middlewares.phpmyadmin.headers.customrequestheaders.accessControlAllowCredentials=true'
      - 'traefik.http.middlewares.phpmyadmin.headers.customrequestheaders.accessControlMaxAge=100'
      - 'traefik.http.middlewares.phpmyadmin.headers.customrequestheaders.browserXssFilter=true'
      - 'traefik.http.middlewares.phpmyadmin.headers.customrequestheaders.frameDeny=true'
    env_file:
      - ./phpmyadmin/phpmyadmin.config
    depends_on:
      - mysql

  mailhog:
    container_name: mailhog
    restart: unless-stopped
    image: mailhog/mailhog:v1.0.1
    ports:
      - '587:587'
      - '8025:8025'
    labels:
      - 'traefik.enable=true'

  jenkins:
    container_name: jenkins
    restart: unless-stopped
    image: jenkins/jenkins:2.260
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jenkins.entrypoints=https'
      - 'traefik.http.routers.jenkins.rule=Host(`jenkins.aria-portal.local`)'
      - 'traefik.http.routers.jenkins.tls=true'
      - 'traefik.http.middlewares.jenkins.ratelimit.average=100'
      - 'traefik.http.middlewares.jenkins.ratelimit.burst=20'
      - 'traefik.http.middlewares.jenkins.headers.customrequestheaders.contentSecurityPolicy="default-src "none"; script-src "none"; script-src-elem "none"; script-src-attr "none"; style-src "none"; style-src-elem "none"; style-src-attr "none"; img-src "none"; font-src "none";"'
      - 'traefik.http.middlewares.jenkins.headers.customrequestheaders.accessControlAllowOriginList=jenkins.aria-portal.local'
      - 'traefik.http.middlewares.jenkins.headers.customrequestheaders.accessControlAllowMethods=GET, POST, OPTIONS'
      - 'traefik.http.middlewares.jenkins.headers.customrequestheaders.accessControlAllowCredentials=true'
      - 'traefik.http.middlewares.jenkins.headers.customrequestheaders.accessControlMaxAge=100'
      - 'traefik.http.middlewares.jenkins.headers.customrequestheaders.browserXssFilter=true'
      - 'traefik.http.middlewares.jenkins.headers.customrequestheaders.frameDeny=true'
